apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: gcp-clouddeploy-gke-template
deploy:
  helm:
    releases:
      - name: gcp-clouddeploy-gke-template
        chartPath: helm
profiles:
  - name: staging
    deploy:
      helm:
        releases:
          - name: gcp-clouddeploy-gke-template
            chartPath: helm
            valuesFiles:
              - helm/values-staging.yaml
              - helm/values-dynamic.yaml
  - name: production
    deploy:
      helm:
        releases:
          - name: gcp-clouddeploy-gke-template
            chartPath: helm
            valuesFiles:
              - helm/values-production.yaml
              - helm/values-dynamic.yaml
