apiVersion: v1
kind: Service
metadata:
  name: gcp-clouddeploy-gke-template
  labels:
    app: gcp-clouddeploy-gke-template
spec:
  type: LoadBalancer
  selector:
    app: gcp-clouddeploy-gke-template
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
